### ISSUE TITLE
Unable to connect to rabbitmq container if spark is run in a docker container

### ISSUE THREAD

**Issue by vvsh** [Stratio/spark-rabbitmq#102]
Hi,

I am not able to run spark streaming app in docker container that reads messages from RabbitMQ:

Spark code:

    Map<String, String> rabbitMQParams = new HashMap<>();
    rabbitMQParams.put("host", "rabbitmq");
    rabbitMQParams.put("queueName", "dataset-loaded");
    JavaReceiverInputDStream<String> receiverStream = RabbitMQUtils.createJavaStream(streamingContext, String.class, rabbitMQParams, delivery -> new String(delivery.getBody()));
    receiverStream.foreachRDD((VoidFunction<JavaRDD<String>>) (rdd) -> {
            List<String> ids = rdd.collect();
            System.out.println(ids);
        });
    });
    streamingContext.start();
    streamingContext.awaitTermination();

Docker-compose part:

    version: '3'

    services:
      spark-jobserver:
        build: spark-jobserver/
        ports:
          - 8090
        depends_on:
          - rabbitmq
        links:
          - rabbitmq
        environment:
          SPARK_MASTER: "local[4]"
        restart: always

      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672
          - "15672:15672"
        restart: always
        volumes:
          - rabbitmq-data:/var/lib/rabbitmq

    volumes:
      rabbitmq-data:
        external: false

Spark is run using spark job server.

Log:

17/03/18 09:12:12 DEBUG Consumer: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Connecting to virtual host /
17/03/18 09:12:12 DEBUG Consumer: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Setting userName guest
17/03/18 09:12:12 DEBUG Consumer: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Setting password guest
17/03/18 09:12:12 DEBUG RecurringTimer: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Callback for BlockGenerator called at time 1489828332400
17/03/18 09:12:12 ERROR RabbitMQReceiver: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Could not connect
17/03/18 09:12:12 INFO ReceiverSupervisorImpl: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Called receiver 0 onStart
17/03/18 09:12:12 INFO ReceiverSupervisorImpl: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Waiting for receiver to be stopped
17/03/18 09:12:12 WARN ReceiverSupervisorImpl: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Restarting receiver with delay 2000 ms: Could not connect
java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:47)
at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:884)
at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:839)
at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:661)
at org.apache.spark.streaming.rabbitmq.consumer.Consumer$.org$apache$spark$streaming$rabbitmq$consumer$Consumer$$addConnection(Consumer.scala:269)
at org.apache.spark.streaming.rabbitmq.consumer.Consumer$$anonfun$1.apply(Consumer.scala:251)
at org.apache.spark.streaming.rabbitmq.consumer.Consumer$$anonfun$1.apply(Consumer.scala:251)
at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
at scala.collection.AbstractMap.getOrElse(Map.scala:59)
at org.apache.spark.streaming.rabbitmq.consumer.Consumer$.getChannel(Consumer.scala:251)
at org.apache.spark.streaming.rabbitmq.consumer.Consumer$.apply(Consumer.scala:207)
at org.apache.spark.streaming.rabbitmq.receiver.RabbitMQReceiver$$anonfun$3.apply(RabbitMQInputDStream.scala:60)
at org.apache.spark.streaming.rabbitmq.receiver.RabbitMQReceiver$$anonfun$3.apply(RabbitMQInputDStream.scala:59)
at scala.util.Try$.apply(Try.scala:192)
at org.apache.spark.streaming.rabbitmq.receiver.RabbitMQReceiver.onStart(RabbitMQInputDStream.scala:59)
at org.apache.spark.streaming.receiver.ReceiverSupervisor.startReceiver(ReceiverSupervisor.scala:149)
at org.apache.spark.streaming.receiver.ReceiverSupervisor.start(ReceiverSupervisor.scala:131)
at org.apache.spark.streaming.scheduler.ReceiverTracker$ReceiverTrackerEndpoint$$anonfun$9.apply(ReceiverTracker.scala:597)
at org.apache.spark.streaming.scheduler.ReceiverTracker$ReceiverTrackerEndpoint$$anonfun$9.apply(ReceiverTracker.scala:587)
at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1976)
at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1976)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
at org.apache.spark.scheduler.Task.run(Task.scala:86)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
17/03/18 09:12:12 INFO ReceiverSupervisorImpl: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Stopping receiver with message: Restarting receiver with delay 2000ms: Could not connect: java.net.ConnectException: Connection refused (Connection refused)
17/03/18 09:12:12 INFO RabbitMQReceiver: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Closed all RabbitMQ connections
17/03/18 09:12:12 INFO ReceiverSupervisorImpl: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Called receiver onStop
17/03/18 09:12:12 INFO ReceiverSupervisorImpl: [akka://JobServer/user/jobManager-20-97fe-68a33a5dd1a8] - Deregistering receiver 0

At the same time I have spring boot application that is able to connect to rabbitmq and send messages, logs from rabbitmq:

2017-03-17T22:08:35.814951100Z 
=INFO REPORT==== 17-Mar-2017::22:08:35 ===
accepting AMQP connection <0.309.0> (172.18.0.6:60810 -> 172.18.0.4:5672)
2017-03-17T22:08:35.925919300Z 
=INFO REPORT==== 17-Mar-2017::22:08:35 ===
Connection <0.309.0> (172.18.0.6:60810 -> 172.18.0.4:5672) has a client-provided name: rabbitConnectionFactory#0

What might be the reason?
Thanks

**Comment by jniebuhr** [comment]
I think the parameter is called `hosts`. Unless you're using some other version where it is `host`

And you don't really need `links` and `depends_on`. If you put a link it'll also mean it depends on the other container.

**Comment by vvsh** [comment]
I will try hosts, thank you!

As for links and depends_on, I did not know this, thank you.

**Comment by compae** [comment]
Thanks for all
