### ISSUE TITLE
NoSuchMethodError com.google.common.util.concurrent.RateLimiter.acquire()V

### ISSUE THREAD

**Issue by Raveesh** [Stratio/Spark-RabbitMQ#21]
I am using spark 1.5.1 with cassandra connector 2.1 and the latest Rabbitmq-Receiver. 
There is already a few confusions w.r.t spark and cassandra guava library clash. spark needs guava 14.jar and cassandra connector needs guava 15+.  I have set the library path in spark in order to pickup the guava 16 jar. However, I seem to be getting the above mentioned error from RabbitMQInputDStream  line 97 i.e " store(new Predef.String(delivery.getBody))"

The full stack trace is as follows 
```
2015-12-04 18:25:16 INFO  RabbitMQReceiver:143 - created new connection and channel
2015-12-04 18:25:16 INFO  RabbitMQReceiver:66 - onStart, Connecting..
2015-12-04 18:25:16 INFO  RabbitMQReceiver:125 - declaring direct queue
2015-12-04 18:25:16 INFO  ReceiverSupervisorImpl:59 - Called receiver onStart
2015-12-04 18:25:16 INFO  ReceiverSupervisorImpl:59 - Waiting for receiver to be stopped
2015-12-04 18:25:16 INFO  RabbitMQReceiver:88 - RabbitMQ Input waiting for messages
2015-12-04 18:25:16 INFO  RabbitMQReceiver:90 - start consuming data
2015-12-04 18:25:16 INFO  RabbitMQReceiver:94 - waiting for data
2015-12-04 18:25:16 INFO  RabbitMQReceiver:96 - storing data
2015-12-04 18:25:16 ERROR RabbitMQReceiver:85 - Got this unknown exception: java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()V
java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()V
        at org.apache.spark.streaming.receiver.RateLimiter.waitToPush(RateLimiter.scala:42)
        at org.apache.spark.streaming.receiver.BlockGenerator.addData(BlockGenerator.scala:160)
        at org.apache.spark.streaming.receiver.ReceiverSupervisorImpl.pushSingle(ReceiverSupervisorImpl.scala:118)
        at org.apache.spark.streaming.receiver.Receiver.store(Receiver.scala:119)
        at com.stratio.receiver.RabbitMQReceiver.com$stratio$receiver$RabbitMQReceiver$$receive(RabbitMQInputDStream.scala:97)
        at com.stratio.receiver.RabbitMQReceiver$$anon$1.run(RabbitMQInputDStream.scala:69)
2015-12-04 18:25:16 INFO  RabbitMQReceiver:104 - it has been stopped
2015-12-04 18:25:16 WARN  ReceiverSupervisorImpl:92 - Restarting receiver with delay 2000 ms: Trying to connect again
2015-12-04 18:25:16 INFO  ReceiverSupervisorImpl:59 - Stopping receiver with message: Restarting receiver with delay 2000ms: Trying to connect again:
2015-12-04 18:25:16 INFO  RabbitMQReceiver:79 - onStop, doing nothing.. relaxing...
2015-12-04 18:25:16 INFO  ReceiverSupervisorImpl:59 - Called receiver onStop
2015-12-04 18:25:16 INFO  ReceiverSupervisorImpl:59 - Deregistering receiver 0
2015-12-04 18:25:16 ERROR ReceiverTracker:75 - Deregistered receiver for stream 0: Restarting receiver with delay 2000ms: Trying to connect again
```

Any pointers on resolving this issue . ? I have tried using guava 18.0 , guava 19.* jars as well . But the error seems to remain .

**Comment by danielcsant** [comment]
Hi,

We currently does not support Spark 1.5. You can try to upgrade the project to use that Spark version. 

Regards

**Comment by compae** [comment]
Hi Raveesh,

In the PR #41 we update to Spark 1.6 and 1.5 versions. 

If you have more problems, please open new issues.

Thanks for all.
