### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/Logging

### ISSUE THREAD

**Issue by ArtemZubenko-Intelliseclabs** [Stratio/spark-rabbitmq#81]
Hello Everyone, 

I'm seeking your expert advice on the issue I'm having... I am receiving the following exception at the run time while creating java stream. Does anyone know how to fix it? Appreciate your advice.

Version of Rabbitmq I am running is 3.6.1
Version of Apache Spark is 2.0.1
Java version is 1.8

```
2016-11-17 22:40:36 DEBUG ClosureCleaner:58 -  +++ closure <function1> (org.apache.spark.streaming.rabbitmq.RabbitMQUtils$$anonfun$3) is now cleaned +++
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/Logging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.streaming.rabbitmq.RabbitMQUtils$.createStream(RabbitMQUtils.scala:44)
	at org.apache.spark.streaming.rabbitmq.RabbitMQUtils$.createJavaStream(RabbitMQUtils.scala:98)
	at org.apache.spark.streaming.rabbitmq.RabbitMQUtils.createJavaStream(RabbitMQUtils.scala)
	at com.test.Runner.main(Runner.java:49)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Logging
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
2016-11-17 22:40:36 INFO  SparkContext:54 - Invoking stop() from shutdown hook

```
My pom.xml

```xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>StreamingTest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_2.11</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.stratio.receiver</groupId>
            <artifactId>spark-rabbitmq_1.6</artifactId>
            <version>0.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.6.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.6.5</version>
        </dependency>
    </dependencies>

</project>

```
My Java Class

```java

package com.test;

import org.apache.spark.SparkConf;
import org.apache.spark.api.java.function.Function;
import org.apache.spark.streaming.Duration;
import org.apache.spark.streaming.api.java.JavaReceiverInputDStream;
import org.apache.spark.streaming.api.java.JavaStreamingContext;
import org.apache.spark.streaming.rabbitmq.RabbitMQUtils;

import java.util.HashMap;
import java.util.Map;

public class Runner {
    public static void main(String[] args) {
        try {
            JavaStreamingContext javaStreamingContext = new JavaStreamingContext(new SparkConf().setAppName("JavaRabbitMQConsumer").setMaster("local[3]"), new Duration(10000));
            Map<String, String> params = new HashMap<String, String>();
            params.put("hosts", "localhost");
            params.put("queueName", "text-queue");
            params.put("exchangeName", "message-processor-exchange");
            params.put("vHost", "/");
            params.put("userName", "guest");
            params.put("password", "guest");

            Function<byte[], String> messageHandler = new Function<byte[], String>() {

                public String call(byte[] message) {
                    return new String(message);
                }
            };

            // Receiving exception here
            JavaReceiverInputDStream<String> messages =
                    RabbitMQUtils.createJavaStream(javaStreamingContext, String.class, params, messageHandler);

            messages.print();

            javaStreamingContext.start();
            javaStreamingContext.awaitTermination();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}


```
Please let me know if you need more details

Thanks, 

Artem

**Comment by nelsou** [comment]
You cannot use Spark +2.0 with RabbitMQ receiver 1.6. Use Spark 1.6 isntead.

**Comment by compae** [comment]
Thanks for the response @nelsou .

@ArtemZubenko-Intelliseclabs in the next days we update the Spark version to 2.0 and you can use the library with this Spark version.

Regards compae
